More preparations for UWSM See CHANGELOG.md for more info

diff --git a/Configs/.local/bin/hyde-shell b/Configs/.local/bin/hyde-shell
--- a/Configs/.local/bin/hyde-shell
+++ b/Configs/.local/bin/hyde-shell
@@ -1,22 +1,6 @@
 #!/usr/bin/env bash
 # This script will soon be used to resolve $PATHS and LIB_DIR specific to hyde
 # wallbash script can source this script to resolve the paths cleanly on a separate shell
-
-if [[ -z "${BASH_SOURCE[0]}" ]]; then
-    EXECUTABLE="${0}"
-else
-    EXECUTABLE="${BASH_SOURCE[0]}"
-fi
-
-BIN_DIR=$(dirname "$(which "${EXECUTABLE:-hyde-shell}")")
-LIB_DIR=$(realpath "${BIN_DIR}/../lib")
-SHARE_DIR=$(realpath "${BIN_DIR}/../share")
-PATH="${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:$BIN_DIR:$LIB_DIR/hyde:$PATH" #! I added this to the PATH to make sure that the hyde commands are available in the shell
-# Define hyde scripts search paths (colon-separated, user configurable)
-HYDE_SCRIPTS_PATH="${HYDE_SCRIPTS_PATH:-${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:${LIB_DIR}/hyde}:${XDG_DATA_HOME}/waybar/scripts:${XDG_CONFIG_HOME}/waybar/scripts"
-
-export BIN_DIR LIB_DIR SHARE_DIR PATH HYDE_SCRIPTS_PATH
-
 python_initialized() {
 
     python "${LIB_DIR}/hyde/pyutils/pip_env.py" rebuild
@@ -44,19 +28,6 @@ EOF
     #? Use sed to remove any shebang hints to avoid conflicts with "eval"
     command cat "${LIB_DIR}/hyde/globalcontrol.sh"
 }
-
-# If args is init or --init, print initialization script
-if [[ "$1" == "init" || "$1" == "--init" ]]; then
-    initialized
-    exit 0
-else
-    export HYDE_SHELL_INIT=1
-fi
-# shellcheck disable=SC1091
-if ! source "${LIB_DIR}/hyde/globalcontrol.sh"; then
-    echo "Error: Could not load HyDE, broken installation?"
-    exit 1
-fi
 
 USAGE() {
 
@@ -460,6 +431,47 @@ run_command() {
         done
     fi
 }
+
+#*--------------------------------------------------------------------------------
+
+if [[ -z "${BASH_SOURCE[0]}" ]]; then
+    EXECUTABLE="${0}"
+else
+    EXECUTABLE="${BASH_SOURCE[0]}"
+fi
+
+BIN_DIR=$(dirname "$(which "${EXECUTABLE:-hyde-shell}")")
+LIB_DIR=$(realpath "${BIN_DIR}/../lib")
+SHARE_DIR=$(realpath "${BIN_DIR}/../share")
+PATH="${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:$BIN_DIR:$LIB_DIR/hyde:$PATH" #! I added this to the PATH to make sure that the hyde commands are available in the shell
+# Define hyde scripts search paths (colon-separated, user configurable)
+HYDE_SCRIPTS_PATH="${HYDE_SCRIPTS_PATH:-${XDG_CONFIG_HOME:-$HOME/.config}/hyde/scripts:${LIB_DIR}/hyde}:${XDG_DATA_HOME}/waybar/scripts:${XDG_CONFIG_HOME}/waybar/scripts"
+
+export BIN_DIR LIB_DIR SHARE_DIR PATH HYDE_SCRIPTS_PATH
+
+#? Handler for launchers that does not require other env variables
+#*--------------------------------------------------------------------------------
+if [[ "${1}" == "app" ]]; then
+    export PATH="${HYDE_SCRIPTS_PATH}:${PATH}"
+    shift
+    exec app2unit.sh "$@"
+fi
+#*--------------------------------------------------------------------------------
+
+# If args is init or --init, print initialization script
+if [[ "$1" == "init" || "$1" == "--init" ]]; then
+    initialized
+    exit 0
+else
+    export HYDE_SHELL_INIT=1
+fi
+# shellcheck disable=SC1091
+if ! source "${LIB_DIR}/hyde/globalcontrol.sh"; then
+    echo "Error: Could not load HyDE, broken installation?"
+    exit 1
+fi
+
+#*--------------------------------------------------------------------------------
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
 
